version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd package
      - zip -r ../deployment.zip .
      - cd ..
      - zip deployment.zip lambda_function.py

artifacts:
  files:
    - deployment.zip
    - deployspec.yml