version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd package
      - zip -r ../deployment.zip .
      - cd ..
      - zip deployment.zip search_photos.py
  post_build:
    commands:
      - echo "Uploading deployment.zip to S3..."
      - aws s3 cp deployment.zip arn:aws:s3:::lambda-test-23890/deployment.zip
      - echo "Upload DONE!!"

artifacts:
  files:
    - "deployment.zip"