version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd package
      - zip -r ../deployment.zip .
      - cd ..
      - zip deployment.zip search_photos.py
  post_build:
    commands:
      - echo "Upload deployment.zip to S3..."
      - aws s3 cp deployment.zip s3://codepipeline-us-east-1-848523133671/deployment.zip
      - echo "Build DONE!!"

artifacts:
  files:
    - "deployment.zip"